<?xml version="1.0" encoding="utf-8"?>
<!DOCTYPE Doctors[
  <!ELEMENT Doctors (Passenger+)>
  <!ELEMENT Passenger (Survival, Name, Sex, Age)>
  <!ATTLIST Passenger PassengerId ID #REQUIRED>
  <!ELEMENT Survival (#PCDATA)>
  <!ELEMENT Name (#PCDATA)>
  <!ELEMENT Sex (#PCDATA)>
  <!ELEMENT Age (#PCDATA)>
]>
<Doctors>
  <?refreshData daily?><![CDATA[<?xml version="1.0"?>]]><Passenger PassengerId="246"><Survival>0</Survival><Name>Minahan Dr. William Edward</Name><Sex>male</Sex><Age>44</Age><!--0 Minahan Dr. William Edward male 44 --></Passenger><Passenger PassengerId="318"><Survival>0</Survival><Name>Moraweck Dr. Ernest</Name><Sex>male</Sex><Age>54</Age><!--0 Moraweck Dr. Ernest male 54 --></Passenger><Passenger PassengerId="399"><Survival>0</Survival><Name>Pain Dr. Alfred</Name><Sex>male</Sex><Age>23</Age><!--0 Pain Dr. Alfred male 23 --></Passenger><Passenger PassengerId="633"><Survival>1</Survival><Name>Stahelin-Maeglin Dr. Max</Name><Sex>male</Sex><Age>32</Age><!--1 Stahelin-Maeglin Dr. Max male 32 --></Passenger><Passenger PassengerId="661"><Survival>1</Survival><Name>Frauenthal Dr. Henry William</Name><Sex>male</Sex><Age>50</Age><!--1 Frauenthal Dr. Henry William male 50 --></Passenger><Passenger PassengerId="767"><Survival>0</Survival><Name>Brewe Dr. Arthur Jackson</Name><Sex>male</Sex><Age>45</Age><!--0 Brewe Dr. Arthur Jackson male 45 --></Passenger><Passenger PassengerId="797"><Survival>1</Survival><Name>Leader Dr. Alice (Farnham)</Name><Sex>female</Sex><Age>49</Age><!--1 Leader Dr. Alice (Farnham) female 49 --></Passenger><!----></Doctors>
<!---->